spring.application.name=prashansa-backend

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.session.cookie-name=PRASHANSA_SESSION
app.session.max-age-seconds=604800

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.upload.dir=./uploads